const Api = {
	blogCount: '/blogCount',
	homeBlog: '/homeBlog',
	homePage: '/homePage',
	blogDetail: '/blogDetail',
	nearBlog: '/nearBlog',
	blogComment: '/blogComment',
	addBlogComment: '/addBlogComment',
	addBlogLike: '/addBlogLike',
	walkingBlog: '/walkingBlog',
	walkingBlogDetail: '/walkingBlogDetail',
	walkingBlogComment: '/walkingBlogComment',
	addWalkingBlogComment: '/addWalkingBlogComment',
	nearWalkingBlog: '/nearWalkingBlog',
	bookList: '/bookList',
	bookLike: '/bookLike',
	archiveCondition: '/archiveCondition',
	archiveAll: '/archiveAll',
	categories: '/categories',
	tags: '/tags',
	blogCountForYear: '/blogCountForYear',
	siteYear: '/siteYear',
	boardComment: '/boardComment',
	boardCommentMore: '/boardCommentMore',
	addBoardComment: '/addBoardComment',
	subscribe: '/subscribe',
	siteNum: '/siteNum',
	unsubconfirm: '/unsubconfirm',
	cancelSub: '/cancelSub',

};

export default Api;